name: cdk list

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        node-version: ["14"]
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          npm install -g aws-cdk
          pip install -r requirements.txt

      - name: cdk list
        run: |
          cdk list
      
